Infotap\AdminBundle\Entity\Department:
    type: entity
    table: department
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        imgUrl:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: img_url
        description:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
